### ISSUE TITLE
Missing file articles_timeDict_103630.pkl

### ISSUE THREAD

**Issue by igor17400** [summmeer/session-based-news-recommendation#10]
Apologies for any inconvenience, and thank you for making the code available! 

I encountered an issue while attempting to execute the initial preprocessing step. It seems that I couldn't locate the file `articles_timeDict_103630.pkl`. 

```
No such file or directory: articles_timeDict_103630.pkl
```

Could you please advise on how I can obtain or download this file?

**Comment by summmeer** [comment]
Please refer to: https://github.com/summmeer/session-based-news-recommendation/issues/6#issuecomment-1233830425

**Comment by igor17400** [comment]
Thank you very much @summmeer !
It worked.
