### ISSUE TITLE
Doubt about TimeDistributed  Layer

### ISSUE THREAD

**Issue by igor17400** [summmeer/session-based-news-recommendation#11]
I apologize if this question seems obvious, but I'm seeking clarification regarding the use of the `TimeDistributed` layer in the following code snippets. From my understanding, the model already incorporates time as an input dimension. Could someone please explain the necessity of this layer?

```
titlebeh=TimeDistributed(title_encoder)(his_title_input)
bodybeh=TimeDistributed(bodyEncodert)(his_body_input)
```

Thank you very much!

**Comment by summmeer** [comment]
Hi, this is the code for the baseline CPRS. This method does not utilize physical "Time" as the input. Here, `TimeDistributed` is a Keras wrapped layer that can process the sequence of articles' titles or bodies and make each of them through the respective encoder. You can search and find the use of `TimeDistributed`.

**Comment by igor17400** [comment]
@summmeer got it, thank you very much for your reply!
