### ISSUE TITLE
关于论文中设备硬件的问题

### ISSUE THREAD

**Issue by nibyig** [summmeer/session-based-news-recommendation#3]
您好，我在论文复现的时候出现了运行时间过长的问题，我们想确定一下是否是由于系统硬件不够要求，所以想问一下该论文中所使用的cpu规格

**Comment by summmeer** [comment]
CPU: Intel Xeon E5-2640 v3 2.6GHz (8 cores), GPU: GTX1080Ti. It wouldn't be too long when training. There may be other bugs, and it would be better if you share your output log.

**Comment by summmeer** [comment]
The run time bugs are from the computing of ILD and unEXP score for Globo dataset. I will update the file.
