### ISSUE TITLE
No such file or directory: './data/globo/TCAR-mid/Normal-2/item_freq_dict_norm_1.txt'

### ISSUE THREAD

**Issue by vingovan** [summmeer/session-based-news-recommendation#5]
Hi,
I try to experiment with your code but i got error
` No such file or directory: './data/globo/TCAR-mid/Normal-2/item_freq_dict_norm_1.txt'`
I read your code but i could not see how to generate item_freq_dict_norm_1.txt
how to generate this file?
Thank you.

**Comment by summmeer** [comment]
Thanks for your attention. This file is used to compute ESIR score, which we didn't use at last, so this line can be removed. I think I already update this in my code, you can pull and try again.
