### ISSUE TITLE
Publish time for MIND news articles

### ISSUE THREAD

**Issue by roynirmal** [summmeer/session-based-news-recommendation#6]
Hey can you share the file for reading publish time of news articles in the MIND dataset?

**Comment by roynirmal** [comment]
Specifically, I am looking for the file `articles_timeDict_103630.pkl`

**Comment by summmeer** [comment]
[articles_timeDict_103630.pkl.gz](https://github.com/summmeer/session-based-news-recommendation/files/9467559/articles_timeDict_103630.pkl.gz)

The publishing time is crawled from the website and this is the pkl file. Wish this can help you @roynirmal .

**Comment by roynirmal** [comment]
Thanks!
